[toolchain]
# anchor_version = "0.32.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cascade_splits = "SPL1T3rERcu6P6dyBiG7K8LUr21CssZqDAszwANzNMB"

[programs.devnet]
cascade_splits = "SPL1T3rERcu6P6dyBiG7K8LUr21CssZqDAszwANzNMB"

[programs.mainnet]
cascade_splits = "SPL1T3rERcu6P6dyBiG7K8LUr21CssZqDAszwANzNMB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
upgradeable = true

[scripts]
test = "pnpm vitest run tests/"
